<?php

/**
 * This is the model base class for the table "radio_track".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RadioTrack".
 *
 * Columns in table "radio_track" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $title
 * @property integer $radio_type
 * @property string $create_datetime
 *
 */
abstract class BaseRadioTrack extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'radio_track';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'RadioTrack|RadioTracks', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, radio_type', 'required'),
			array('radio_type', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('create_datetime', 'safe'),
			array('create_datetime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, radio_type, create_datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'radio_type' => Yii::t('app', 'Radio Type'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('radio_type', $this->radio_type);
		$criteria->compare('create_datetime', $this->create_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}