<?php

/**
 * This is the model base class for the table "radio".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Radio".
 *
 * Columns in table "radio" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $user_login
 * @property integer $radio_type
 * @property integer $finish_type
 * @property integer $is_online
 * @property string $start_datetime
 * @property string $end_datetime
 * @property string $last_update_datetime
 * @property string $next_update_datetime
 * @property integer $captcha_errors
 * @property string $alias
 *
 */
abstract class BaseRadio extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'radio';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Radio|Radios', $n);
	}

	public function rules() {
		return array(
			array('user_id, user_login', 'required'),
			array('user_id, radio_type, finish_type, is_online, captcha_errors', 'numerical', 'integerOnly'=>true),
			array('user_login, alias', 'length', 'max'=>255),
			array('start_datetime, end_datetime, last_update_datetime, next_update_datetime', 'safe'),
			array('radio_type, finish_type, is_online, start_datetime, end_datetime, last_update_datetime, next_update_datetime, captcha_errors, alias', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, user_login, radio_type, finish_type, is_online, start_datetime, end_datetime, last_update_datetime, next_update_datetime, captcha_errors, alias', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'radio_type' => Yii::t('app', 'Radio Type'),
			'finish_type' => Yii::t('app', 'Finish Type'),
			'is_online' => Yii::t('app', 'Is Online'),
			'start_datetime' => Yii::t('app', 'Start Datetime'),
			'end_datetime' => Yii::t('app', 'End Datetime'),
			'last_update_datetime' => Yii::t('app', 'Last Update Datetime'),
			'next_update_datetime' => Yii::t('app', 'Next Update Datetime'),
			'captcha_errors' => Yii::t('app', 'Captcha Errors'),
			'alias' => Yii::t('app', 'Captcha Alias'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('radio_type', $this->radio_type);
		$criteria->compare('finish_type', $this->finish_type);
		$criteria->compare('is_online', $this->is_online);
		$criteria->compare('start_datetime', $this->start_datetime, true);
		$criteria->compare('end_datetime', $this->end_datetime, true);
		$criteria->compare('last_update_datetime', $this->last_update_datetime, true);
		$criteria->compare('next_update_datetime', $this->next_update_datetime, true);
		$criteria->compare('captcha_errors', $this->captcha_errors);
		$criteria->compare('alias', $this->alias, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}