<?php

/**
 * This is the model base class for the table "community_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CommunityUser".
 *
 * Columns in table "community_user" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $community_id
 * @property integer $user_id
 * @property string $create_datetime
 *
 */
abstract class BaseCommunityUser extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'community_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CommunityUser|CommunityUsers', $n);
	}

	public static function representingColumn() {
		return 'create_datetime';
	}

	public function rules() {
		return array(
			array('community_id, user_id, create_datetime', 'required'),
			array('community_id, user_id', 'numerical', 'integerOnly'=>true),
			array('id, community_id, user_id, create_datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'community_id' => Yii::t('app', 'Community'),
			'user_id' => Yii::t('app', 'User'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('community_id', $this->community_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('create_datetime', $this->create_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}