<?php

/**
 * This is the model base class for the table "subscribe_debate".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SubscribeDebate".
 *
 * Columns in table "subscribe_debate" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $subscribe_user_id
 * @property integer $item_id
 * @property integer $item_type
 * @property string $item_title
 * @property integer $owner_item_user_id
 * @property string $create_datetime
 * @property integer $is_view
 * @property string $view_datetime
 *
 */
abstract class BaseSubscribeDebate extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'subscribe_debate';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SubscribeDebate|SubscribeDebates', $n);
	}

	public static function representingColumn() {
		return 'item_title';
	}

	public function rules() {
		return array(
			array('subscribe_user_id, item_id, item_type, owner_item_user_id', 'required'),
			array('subscribe_user_id, item_id, item_type, owner_item_user_id, is_view', 'numerical', 'integerOnly'=>true),
			array('item_title', 'length', 'max'=>255),
			array('create_datetime, view_datetime', 'safe'),
			array('item_title, create_datetime, is_view, view_datetime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('subscribe_user_id, item_id, item_type, item_title, owner_item_user_id, create_datetime, is_view, view_datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'subscribe_user_id' => Yii::t('app', 'Subscribe User'),
			'item_id' => Yii::t('app', 'Item'),
			'item_type' => Yii::t('app', 'Item Type'),
			'item_title' => Yii::t('app', 'Item Title'),
			'owner_item_user_id' => Yii::t('app', 'Owner Item User'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'is_view' => Yii::t('app', 'Is View'),
			'view_datetime' => Yii::t('app', 'View Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('subscribe_user_id', $this->subscribe_user_id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('item_type', $this->item_type);
		$criteria->compare('item_title', $this->item_title, true);
		$criteria->compare('owner_item_user_id', $this->owner_item_user_id);
		$criteria->compare('create_datetime', $this->create_datetime, true);
		$criteria->compare('is_view', $this->is_view);
		$criteria->compare('view_datetime', $this->view_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}