<?php

/**
 * This is the model base class for the table "gallery_video".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GalleryVideo".
 *
 * Columns in table "gallery_video" available as properties of the model,
 * followed by relations of table "gallery_video" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property string $description
 * @property integer $video_type
 * @property integer $is_comment
 * @property integer $is_activated
 * @property integer $is_deleted
 * @property string $create_datetime
 * @property string $update_datetime
 * @property string $link
 * @property string $video_id
 * @property integer $rating
 * @property integer $view_role
 * @property integer $is_moder_deleted
 * @property string $user_deleted_datetime
 *
 * @property User $user
 *
 * @package application.gallery.models
 */
abstract class BaseGalleryVideo extends MyAR
{
    /**
     * @param string $className
     * @return BaseGalleryVideo
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'gallery_video';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'GalleryVideo|GalleryVideos', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return 'title';
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('user_id, title, create_datetime, update_datetime, view_role', 'required'),
			array('user_id, video_type, is_comment, is_activated, is_deleted, rating, view_role, is_moder_deleted', 'numerical', 'integerOnly'=>true),
			array('title, link, video_id', 'length', 'max'=>255),
			array('user_deleted_datetime', 'length', 'max'=>45),
			array('description', 'safe'),
			array('description, video_type, is_comment, is_activated, is_deleted, link, video_id, rating, is_moder_deleted, user_deleted_datetime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, title, description, video_type, is_comment, is_activated, is_deleted, create_datetime, update_datetime, link, video_id, rating, view_role, is_moder_deleted, user_deleted_datetime', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'video_type' => Yii::t('app', 'Video Type'),
			'is_comment' => Yii::t('app', 'Is Comment'),
			'is_activated' => Yii::t('app', 'Is Activated'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'update_datetime' => Yii::t('app', 'Update Datetime'),
			'link' => Yii::t('app', 'Link'),
			'video_id' => Yii::t('app', 'Video'),
			'rating' => Yii::t('app', 'Rating'),
			'view_role' => Yii::t('app', 'View Role'),
			'is_moder_deleted' => Yii::t('app', 'Is Moder Deleted'),
			'user_deleted_datetime' => Yii::t('app', 'User Deleted Datetime'),
			'user' => null,
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('video_type', $this->video_type);
		$criteria->compare('is_comment', $this->is_comment);
		$criteria->compare('is_activated', $this->is_activated);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('create_datetime', $this->create_datetime, true);
		$criteria->compare('update_datetime', $this->update_datetime, true);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('video_id', $this->video_id, true);
		$criteria->compare('rating', $this->rating);
		$criteria->compare('view_role', $this->view_role);
		$criteria->compare('is_moder_deleted', $this->is_moder_deleted);
		$criteria->compare('user_deleted_datetime', $this->user_deleted_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}