<?php

/**
 * This is the model base class for the table "gallery_image".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GalleryImage".
 *
 * Columns in table "gallery_image" available as properties of the model,
 * followed by relations of table "gallery_image" available as properties of the model.
 *
 * @property integer $id
 * @property integer $album_id
 * @property integer $user_id
 * @property string $title
 * @property string $description
 * @property string $file_name
 * @property string $file_ext
 * @property integer $is_comment
 * @property integer $is_activated
 * @property integer $is_deleted
 * @property string $create_datetime
 * @property integer $is_completed
 * @property integer $rating
 * @property integer $view_role
 * @property integer $is_moder_deleted
 * @property string $user_deleted_datetime
 *
 * @property GalleryAlbum $album
 * @property User $user
 *
 * @package application.gallery.models
 */
abstract class BaseGalleryImage extends MyAR
{
    /**
     * @param string $className
     * @return BaseGalleryImage
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'gallery_image';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'GalleryImage|GalleryImages', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return 'file_name';
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('album_id, user_id, file_name, file_ext, create_datetime, view_role', 'required'),
			array('album_id, user_id, is_comment, is_activated, is_deleted, is_completed, rating, view_role, is_moder_deleted', 'numerical', 'integerOnly'=>true),
			array('title, file_ext', 'length', 'max'=>255),
			array('file_name', 'length', 'max'=>50),
			array('user_deleted_datetime', 'length', 'max'=>45),
			array('description', 'safe'),
			array('title, description, is_comment, is_activated, is_deleted, is_completed, rating, is_moder_deleted, user_deleted_datetime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, album_id, user_id, title, description, file_name, file_ext, is_comment, is_activated, is_deleted, create_datetime, is_completed, rating, view_role, is_moder_deleted, user_deleted_datetime', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
			'album' => array(self::BELONGS_TO, 'GalleryAlbum', 'album_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'album_id' => null,
			'user_id' => null,
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'file_name' => Yii::t('app', 'File Name'),
			'file_ext' => Yii::t('app', 'File Ext'),
			'is_comment' => Yii::t('app', 'Is Comment'),
			'is_activated' => Yii::t('app', 'Is Activated'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'is_completed' => Yii::t('app', 'Is Completed'),
			'rating' => Yii::t('app', 'Rating'),
			'view_role' => Yii::t('app', 'View Role'),
			'is_moder_deleted' => Yii::t('app', 'Is Moder Deleted'),
			'user_deleted_datetime' => Yii::t('app', 'User Deleted Datetime'),
			'album' => null,
			'user' => null,
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('album_id', $this->album_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('file_name', $this->file_name, true);
		$criteria->compare('file_ext', $this->file_ext, true);
		$criteria->compare('is_comment', $this->is_comment);
		$criteria->compare('is_activated', $this->is_activated);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('create_datetime', $this->create_datetime, true);
		$criteria->compare('is_completed', $this->is_completed);
		$criteria->compare('rating', $this->rating);
		$criteria->compare('view_role', $this->view_role);
		$criteria->compare('is_moder_deleted', $this->is_moder_deleted);
		$criteria->compare('user_deleted_datetime', $this->user_deleted_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}