<?php

/**
 * This is the model base class for the table "gallery_audio".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GalleryAudio".
 *
 * Columns in table "gallery_audio" available as properties of the model,
 * followed by relations of table "gallery_audio" available as properties of the model.
 *
 * @property integer $id
 * @property integer $album_id
 * @property integer $user_id
 * @property string $title
 * @property integer $seconds
 * @property integer $item_type
 * @property string $link
 * @property string $create_datetime
 * @property string $update_datetime
 * @property integer $rating
 * @property integer $is_moder_deleted
 * @property integer $is_reported
 * @property integer $is_deleted
 * @property integer $is_activated
 *
 * @property GalleryAlbumAudio $album
 * @property User $user
 */
abstract class BaseGalleryAudio extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gallery_audio';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GalleryAudio|GalleryAudios', $n);
	}

	public static function representingColumn() {
		return 'link';
	}

	public function rules() {
		return array(
			array('album_id, user_id, link, create_datetime, update_datetime', 'required'),
			array('album_id, user_id, seconds, item_type, rating, is_moder_deleted, is_reported, is_deleted, is_activated', 'numerical', 'integerOnly'=>true),
			array('title, link', 'length', 'max'=>255),
			array('title, seconds, item_type, rating, is_moder_deleted, is_reported, is_deleted, is_activated', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, album_id, user_id, title, seconds, item_type, link, create_datetime, update_datetime, rating, is_moder_deleted, is_reported, is_deleted, is_activated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'album' => array(self::BELONGS_TO, 'GalleryAlbumAudio', 'album_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'album_id' => null,
			'user_id' => null,
			'title' => Yii::t('app', 'Title'),
			'seconds' => Yii::t('app', 'Seconds'),
			'item_type' => Yii::t('app', 'Item Type'),
			'link' => Yii::t('app', 'Link'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'update_datetime' => Yii::t('app', 'Update Datetime'),
			'rating' => Yii::t('app', 'Rating'),
			'is_moder_deleted' => Yii::t('app', 'Is Moder Deleted'),
			'is_reported' => Yii::t('app', 'Is Reported'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'is_activated' => Yii::t('app', 'Is Activated'),
			'album' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('album_id', $this->album_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('seconds', $this->seconds);
		$criteria->compare('item_type', $this->item_type);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('create_datetime', $this->create_datetime, true);
		$criteria->compare('update_datetime', $this->update_datetime, true);
		$criteria->compare('rating', $this->rating);
		$criteria->compare('is_moder_deleted', $this->is_moder_deleted);
		$criteria->compare('is_reported', $this->is_reported);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('is_activated', $this->is_activated);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}