<?php

/**
 * This is the model base class for the table "post".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Post".
 *
 * Columns in table "post" available as properties of the model,
 * followed by relations of table "post" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property string $description
 * @property integer $post_type
 * @property integer $is_like
 * @property integer $is_comment
 * @property integer $is_activated
 * @property integer $is_deleted
 * @property string $create_datetime
 * @property string $update_datetime
 * @property integer $rating
 * @property integer $view_role
 * @property integer $is_moder_deleted
 * @property string $user_deleted_datetime
 *
 * @property Opros[] $oproses
 * @property User $user
 * @property Tag[] $tags
 *
 * @package application.post.models
 */
abstract class BasePost extends MyAR
{
    /**
     * @param string $className
     * @return BasePost
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'post';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'Post|Posts', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return 'title';
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('user_id, title, description, post_type, create_datetime, update_datetime, view_role', 'required'),
			array('user_id, post_type, is_like, is_comment, is_activated, is_deleted, rating, view_role, is_moder_deleted', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('user_deleted_datetime', 'length', 'max'=>45),
			array('is_like, is_comment, is_activated, is_deleted, rating, is_moder_deleted, user_deleted_datetime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, title, description, post_type, is_like, is_comment, is_activated, is_deleted, create_datetime, update_datetime, rating, view_role, is_moder_deleted, user_deleted_datetime', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
			'oproses' => array(self::HAS_MANY, 'Opros', 'post_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'tags' => array(self::MANY_MANY, 'Tag', 'post_tag(post_id, tag_id)'),
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
			'tags' => 'PostTag',
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'post_type' => Yii::t('app', 'Post Type'),
			'is_like' => Yii::t('app', 'Is Like'),
			'is_comment' => Yii::t('app', 'Is Comment'),
			'is_activated' => Yii::t('app', 'Is Activated'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'update_datetime' => Yii::t('app', 'Update Datetime'),
			'rating' => Yii::t('app', 'Rating'),
			'view_role' => Yii::t('app', 'View Role'),
			'is_moder_deleted' => Yii::t('app', 'Is Moder Deleted'),
			'user_deleted_datetime' => Yii::t('app', 'User Deleted Datetime'),
			'oproses' => null,
			'user' => null,
			'tags' => null,
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('post_type', $this->post_type);
		$criteria->compare('is_like', $this->is_like);
		$criteria->compare('is_comment', $this->is_comment);
		$criteria->compare('is_activated', $this->is_activated);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('create_datetime', $this->create_datetime, true);
		$criteria->compare('update_datetime', $this->update_datetime, true);
		$criteria->compare('rating', $this->rating);
		$criteria->compare('view_role', $this->view_role);
		$criteria->compare('is_moder_deleted', $this->is_moder_deleted);
		$criteria->compare('user_deleted_datetime', $this->user_deleted_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}