<?php

/**
 * This is the model base class for the table "post_tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PostTag".
 *
 * Columns in table "post_tag" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $post_id
 * @property integer $tag_id
 *
 * @package application.post.models
 */
abstract class BasePostTag extends MyAR
{
    /**
     * @param string $className
     * @return BasePostTag
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'post_tag';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'PostTag|PostTags', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return array(
			'post_id',
			'tag_id',
		);
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('post_id, tag_id', 'required'),
			array('post_id, tag_id', 'numerical', 'integerOnly'=>true),
			array('post_id, tag_id', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'post_id' => null,
			'tag_id' => null,
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('tag_id', $this->tag_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}