<?php

/**
 * This is the model base class for the table "user_silence".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserSilence".
 *
 * Columns in table "user_silence" available as properties of the model,
 * followed by relations of table "user_silence" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $sender_id
 * @property integer $report_id
 * @property string $comment
 * @property string $moder_reason
 * @property string $create_datetime
 * @property string $end_datetime
 *
 * @property User $sender
 * @property User $user
 *
 * @package application.user.models
 */
abstract class BaseUserSilence extends MyAR
{
    /**
     * @param string $className
     * @return BaseUserSilence
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'user_silence';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'UserSilence|UserSilences', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return 'moder_reason';
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('user_id, sender_id, moder_reason, create_datetime, end_datetime', 'required'),
			array('user_id, sender_id, report_id', 'numerical', 'integerOnly'=>true),
			array('comment', 'safe'),
			array('report_id, comment', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, sender_id, report_id, comment, moder_reason, create_datetime, end_datetime', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
			'sender' => array(self::BELONGS_TO, 'User', 'sender_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'sender_id' => null,
			'report_id' => Yii::t('app', 'Report'),
			'comment' => Yii::t('app', 'Comment'),
			'moder_reason' => Yii::t('app', 'Moder Reason'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'end_datetime' => Yii::t('app', 'End Datetime'),
			'sender' => null,
			'user' => null,
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('sender_id', $this->sender_id);
		$criteria->compare('report_id', $this->report_id);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('moder_reason', $this->moder_reason, true);
		$criteria->compare('create_datetime', $this->create_datetime, true);
		$criteria->compare('end_datetime', $this->end_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}