<?php

/**
 * This is the model base class for the table "event_friend".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EventFriend".
 *
 * Columns in table "event_friend" available as properties of the model,
 * followed by relations of table "event_friend" available as properties of the model.
 *
 * @property integer $id
 * @property integer $sender_id
 * @property integer $reciver_id
 * @property string $create_datetime
 *
 * @property User $reciver
 * @property User $sender
 *
 * @package application.event.models
 */
abstract class BaseEventFriend extends MyAR {

    /**
     * @param string $className
     * @return BaseEventFriend
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'event_friend';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'EventFriend|EventFriends', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return 'create_datetime';
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('sender_id, reciver_id, create_datetime', 'required'),
			array('sender_id, reciver_id', 'numerical', 'integerOnly'=>true),
			array('id, sender_id, reciver_id, create_datetime', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
			'reciver' => array(self::BELONGS_TO, 'User', 'reciver_id'),
			'sender' => array(self::BELONGS_TO, 'User', 'sender_id'),
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'sender_id' => null,
			'reciver_id' => null,
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'reciver' => null,
			'sender' => null,
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('sender_id', $this->sender_id);
		$criteria->compare('reciver_id', $this->reciver_id);
		$criteria->compare('create_datetime', $this->create_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}