<?php

/**
 * This is the model base class for the table "community_category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CommunityCategory".
 *
 * Columns in table "community_category" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $title
 *
 */
abstract class BaseCommunityCategory extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'community_category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CommunityCategory|CommunityCategories', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title', 'length', 'max'=>255),
			array('title', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}