<?php

/**
 * This is the model base class for the table "moder_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ModerLog".
 *
 * Columns in table "moder_log" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $moder_id
 * @property integer $item_id
 * @property integer $item_type
 * @property string $moder_reason
 * @property string $create_datetime
 * @property integer $operation_type
 *
 * @package application.moder.models
 *
 */
abstract class BaseModerLog extends MyAR
{
    /**
     * @param string $className
     * @return BaseModerLog
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'moder_log';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'ModerLog|ModerLogs', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return 'moder_reason';
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('moder_id, item_id, item_type, create_datetime, operation_type', 'required'),
			array('moder_id, item_id, item_type, operation_type', 'numerical', 'integerOnly'=>true),
			array('id, moder_id, item_id, item_type, moder_reason, create_datetime, operation_type', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'moder_id' => Yii::t('app', 'Moder'),
			'item_id' => Yii::t('app', 'Item'),
			'item_type' => Yii::t('app', 'Item Type'),
			'moder_reason' => Yii::t('app', 'Moder Reason'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'operation_type' => Yii::t('app', 'Operation Type'),
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('moder_id', $this->moder_id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('item_type', $this->item_type);
		$criteria->compare('moder_reason', $this->moder_reason, true);
		$criteria->compare('create_datetime', $this->create_datetime, true);
		$criteria->compare('operation_type', $this->operation_type);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}