<?php

/**
 * This is the model base class for the table "comment_item".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CommentItem".
 *
 * Columns in table "comment_item" available as properties of the model,
 * followed by relations of table "comment_item" available as properties of the model.
 *
 * @property integer $id
 * @property integer $item_id
 * @property integer $user_id
 * @property integer $user_owner_id
 * @property string $description
 * @property integer $item_type
 * @property string $create_datetime
 * @property string $update_datetime
 * @property integer $is_activated
 * @property integer $is_deleted
 * @property integer $is_moder_deleted
 * @property string $user_deleted_datetime
 *
 * @property User $user
 *
 * @package application.comment.models
 */
abstract class BaseCommentItem extends MyAR {

    /**
     * @param string $className
     * @return BaseCommentItem
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'comment_item';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'CommentItem|CommentItems', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return 'create_datetime';
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('user_owner_id, create_datetime', 'required'),
			array('item_id, user_id, user_owner_id, item_type, is_activated, is_deleted, is_moder_deleted', 'numerical', 'integerOnly'=>true),
			array('description, update_datetime, user_deleted_datetime', 'safe'),
			array('item_id, user_id, description, item_type, update_datetime, is_activated, is_deleted, is_moder_deleted, user_deleted_datetime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, item_id, user_id, user_owner_id, description, item_type, create_datetime, update_datetime, is_activated, is_deleted, is_moder_deleted, user_deleted_datetime', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'item_id' => Yii::t('app', 'Item'),
			'user_id' => null,
			'user_owner_id' => Yii::t('app', 'User Owner'),
			'description' => Yii::t('app', 'Description'),
			'item_type' => Yii::t('app', 'Item Type'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'update_datetime' => Yii::t('app', 'Update Datetime'),
			'is_activated' => Yii::t('app', 'Is Activated'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'is_moder_deleted' => Yii::t('app', 'Is Moder Deleted'),
			'user_deleted_datetime' => Yii::t('app', 'User Deleted Datetime'),
			'user' => null,
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('user_owner_id', $this->user_owner_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('item_type', $this->item_type);
		$criteria->compare('create_datetime', $this->create_datetime, true);
		$criteria->compare('update_datetime', $this->update_datetime, true);
		$criteria->compare('is_activated', $this->is_activated);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('is_moder_deleted', $this->is_moder_deleted);
		$criteria->compare('user_deleted_datetime', $this->user_deleted_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}