<?php

/**
 * This is the model base class for the table "rights".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Rights".
 *
 * Columns in table "rights" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $user_id
 * @property integer $radio
 *
 */
abstract class BaseRights extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'rights';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Rights|Rights', $n);
	}

	public static function representingColumn() {
		return 'user_id';
	}

	public function rules() {
		return array(
			array('user_id', 'required'),
			array('user_id, ', 'numerical', 'integerOnly'=>true),
			array('user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => Yii::t('app', 'User'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}