<?php

/**
 * This is the model base class for the table "user_dj".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserDj".
 *
 * Columns in table "user_dj" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $user_id
 * @property integer $radio_type
 * @property string $game_bank
 * @property string $icq
 * @property string $skype
 *
 */
abstract class BaseUserDj extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_dj';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserDj|UserDjs', $n);
	}

	public static function representingColumn() {
		return 'game_bank';
	}

	public function rules() {
		return array(
			array('user_id, radio_type', 'required'),
			array('user_id, radio_type', 'numerical', 'integerOnly'=>true),
			array('game_bank, icq, skype', 'length', 'max'=>255),
			array('game_bank, icq, skype', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, radio_type, game_bank, icq, skype', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => Yii::t('app', 'User'),
			'radio_type' => Yii::t('app', 'Radio Type'),
			'game_bank' => Yii::t('app', 'Game Bank'),
			'icq' => Yii::t('app', 'Icq'),
			'skype' => Yii::t('app', 'Skype'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('radio_type', $this->radio_type);
		$criteria->compare('game_bank', $this->game_bank, true);
		$criteria->compare('icq', $this->icq, true);
		$criteria->compare('skype', $this->skype, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}