<?php

/**
 * This is the model base class for the table "poll_user_answer".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PollUserAnswer".
 *
 * Columns in table "poll_user_answer" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $poll_id
 * @property integer $answer_id
 * @property integer $user_id
 * @property string $create_datetime
 *
 */
abstract class BasePollUserAnswer extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'poll_user_answer';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PollUserAnswer|PollUserAnswers', $n);
	}

	public static function representingColumn() {
		return 'create_datetime';
	}

	public function rules() {
		return array(
			array('poll_id, answer_id, user_id, create_datetime', 'required'),
			array('poll_id, answer_id, user_id', 'numerical', 'integerOnly'=>true),
			array('poll_id, answer_id, user_id, create_datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'poll_id' => Yii::t('app', 'Poll'),
			'answer_id' => Yii::t('app', 'Answer'),
			'user_id' => Yii::t('app', 'User'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('poll_id', $this->poll_id);
		$criteria->compare('answer_id', $this->answer_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('create_datetime', $this->create_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}