<?php

/**
 * This is the model base class for the table "user_friend".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserFriend".
 *
 * Columns in table "user_friend" available as properties of the model,
 * followed by relations of table "user_friend" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $friend_id
 * @property string $create_datetime
 *
 * @property User $friend
 * @property User $user
 *
 * @package application.user.models
 */
abstract class BaseUserFriend extends MyAR
{
    /**
     * @param string $className
     * @return BaseUserFriend
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'user_friend';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'UserFriend|UserFriends', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return 'create_datetime';
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('user_id, friend_id, create_datetime', 'required'),
			array('user_id, friend_id', 'numerical', 'integerOnly'=>true),
			array('id, user_id, friend_id, create_datetime', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
			'friend' => array(self::BELONGS_TO, 'User', 'friend_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'friend_id' => null,
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'friend' => null,
			'user' => null,
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('friend_id', $this->friend_id);
		$criteria->compare('create_datetime', $this->create_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}