<?php

/**
 * This is the model base class for the table "community_request".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CommunityRequest".
 *
 * Columns in table "community_request" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $community_id
 * @property integer $user_id
 * @property integer $request_status
 * @property string $create_datetime
 * @property integer $isInvite
 *
 */
abstract class BaseCommunityRequest extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'community_request';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CommunityRequest|CommunityRequests', $n);
	}

	public static function representingColumn() {
		return 'create_datetime';
	}

	public function rules() {
		return array(
			array('community_id, user_id, create_datetime', 'required'),
			array('community_id, user_id, request_status, isInvite', 'numerical', 'integerOnly'=>true),
			array('request_status, isInvite', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, community_id, user_id, request_status, create_datetime, isInvite', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'community_id' => Yii::t('app', 'Community'),
			'user_id' => Yii::t('app', 'User'),
			'request_status' => Yii::t('app', 'Request Status'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'isInvite' => Yii::t('app', 'Is Invite'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('community_id', $this->community_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('request_status', $this->request_status);
		$criteria->compare('create_datetime', $this->create_datetime, true);
		$criteria->compare('isInvite', $this->isInvite);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}