<?php

/**
 * This is the model base class for the table "cache_item".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CacheItem".
 *
 * Columns in table "cache_item" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $item_id
 * @property integer $item_type
 * @property string $update_datetime
 *
 */
abstract class BaseCacheEventItem extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cache_event_item';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CacheItem|CacheItems', $n);
	}

	public static function representingColumn() {
		return 'update_datetime';
	}

	public function rules() {
		return array(
			array('item_id, item_type, update_datetime', 'required'),
			array('item_id, item_type', 'numerical', 'integerOnly'=>true),
			array('item_id, item_type, update_datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'item_id' => Yii::t('app', 'Item'),
			'item_type' => Yii::t('app', 'Item Type'),
			'update_datetime' => Yii::t('app', 'Update Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('item_type', $this->item_type);
		$criteria->compare('update_datetime', $this->update_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}