<?php

/**
 * This is the model base class for the table "user_profile".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserProfile".
 *
 * Columns in table "user_profile" available as properties of the model,
 * followed by relations of table "user_profile" available as properties of the model.
 *
 * @property integer $user_id
 * @property string $description
 * @property string $avatar_path
 * @property integer $is_croped
 * @property integer $rating
 *
 * @property User $user
 *
 * @package application.user.models
 */
abstract class BaseUserProfile extends MyAR
{
    /**
     * @param string $className
     * @return BaseUserProfile
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'user_profile';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'UserProfile|UserProfiles', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return 'description';
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('user_id', 'required'),
			array('user_id, is_croped, rating', 'numerical', 'integerOnly'=>true),
			array('avatar_path', 'length', 'max'=>255),
			array('description', 'safe'),
			array('description, avatar_path, is_croped, rating', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, description, avatar_path, is_croped, rating', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'user_id' => null,
			'description' => Yii::t('app', 'Description'),
			'avatar_path' => Yii::t('app', 'Avatar Path'),
			'is_croped' => Yii::t('app', 'Is Croped'),
			'rating' => Yii::t('app', 'Rating'),
			'user' => null,
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('avatar_path', $this->avatar_path, true);
		$criteria->compare('is_croped', $this->is_croped);
		$criteria->compare('rating', $this->rating);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}