<?php

/**
 * This is the model base class for the table "radio".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Radio".
 *
 * Columns in table "radio" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $dj_id
 * @property string $radio_type
 * @property integer $started_at
 * @property integer $ended_at
 * @property string $client
 * @property string $ip
 * @property string $agent
 * @property integer $duration
 * @property integer $counter
 * @property string $ip_change
 * @property integer $radio_session_id
 *
 */
abstract class BaseRadioUser extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'radio_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'RadioUser|RadioUsers', $n);
	}

	public function rules() {
		return array(
			array('dj_id, radio_type', 'required'),
			array('dj_id, radio_type, started_at, ended_at, duration, counter', 'numerical', 'integerOnly'=>true),
			array('client, ip, ip_change', 'length', 'max'=>255),
			array('dj_id, radio_type, started_at, ended_at, client, ip, agent, duration, counter, ip_change, radio_session_id', 'safe'),
			array('client, agent, ip_change, radio_session_id', 'default', 'setOnEmpty' => true, 'value' => null),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' 			=> Yii::t('app', 'ID'),
			'dj_id' 		=> Yii::t('app', 'Dj id'),
			'radio_type' 	=> Yii::t('app', 'Radio Type'),
			'started_at' 	=> Yii::t('app', 'Started at'),
			'ended_at' 		=> Yii::t('app', 'Ended at'),
			'client' 		=> Yii::t('app', 'Client'),
			'ip' 			=> Yii::t('app', 'Ip'),
			'agent' 		=> Yii::t('app', 'Agent'),
			'duration' 		=> Yii::t('app', 'Duration'),
			'counter' 		=> Yii::t('app', 'Counter'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('dj_id', $this->dj_id);
		$criteria->compare('radio_type', $this->radio_type);
		$criteria->compare('started_at', $this->started_at);
		$criteria->compare('ended_at', $this->ended_at);
		$criteria->compare('client', $this->client, true);
		$criteria->compare('ip', $this->ip, true);
		$criteria->compare('agent', $this->agent, true);
		$criteria->compare('duration', $this->duration);
		$criteria->compare('counter', $this->counter);
		$criteria->compare('ip_change', $this->counter, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}