<?php

/**
 * This is the model base class for the table "rating_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RatingUser".
 *
 * Columns in table "rating_user" available as properties of the model,
 * followed by relations of table "rating_user" available as properties of the model.
 *
 * @property integer $user_id
 * @property integer $send_user_id
 * @property integer $value
 * @property string $create_datetime
 *
 * @property User $sendUser
 * @property User $user
 *
 * @package application.rating.models
 */
abstract class BaseRatingUser extends MyAR
{
    /**
     * @param string $className
     * @return BaseRatingUser
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'rating_user';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'RatingUser|RatingUsers', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return 'create_datetime';
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('user_id, send_user_id, create_datetime', 'required'),
			array('user_id, send_user_id, value', 'numerical', 'integerOnly'=>true),
			array('value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, send_user_id, value, create_datetime', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
			'sendUser' => array(self::BELONGS_TO, 'User', 'send_user_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'user_id' => null,
			'send_user_id' => null,
			'value' => Yii::t('app', 'Value'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'sendUser' => null,
			'user' => null,
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('send_user_id', $this->send_user_id);
		$criteria->compare('value', $this->value);
		$criteria->compare('create_datetime', $this->create_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}