<?php

/**
 * This is the model base class for the table "report".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Report".
 *
 * Columns in table "report" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $item_id
 * @property integer $user_owner_id
 * @property integer $item_type
 * @property string $create_datetime
 * @property integer $status
 * @property integer $user_moder_id
 * @property string $moder_reason
 *
 * @package application.report.models
 */
abstract class BaseReport extends MyAR
{
    /**
     * @param string $className
     * @return BaseReport
     */
    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

    /**
     * @return string
     */
    public function tableName() {
		return 'report';
	}

    /**
     * @param int $n
     * @return string
     */
    public static function label($n = 1) {
		return Yii::t('app', 'Report|Reports', $n);
	}

    /**
     * @return array|string
     */
    public static function representingColumn() {
		return 'create_datetime';
	}

    /**
     * @return array
     */
    public function rules() {
		return array(
			array('user_id, item_id, user_owner_id, item_type, create_datetime', 'required'),
			array('user_id, item_id, user_owner_id, item_type, status', 'numerical', 'integerOnly'=>true),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, item_id, user_owner_id, item_type, create_datetime, status', 'safe', 'on'=>'search'),
		);
	}

    /**
     * @return array
     */
    public function relations() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function pivotModels() {
		return array(
		);
	}

    /**
     * @return array
     */
    public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'item_id' => Yii::t('app', 'Item'),
			'user_owner_id' => Yii::t('app', 'User Owner'),
			'item_type' => Yii::t('app', 'Item Type'),
			'create_datetime' => Yii::t('app', 'Create Datetime'),
			'status' => Yii::t('app', 'Status'),
		);
	}

    /**
     * @return CActiveDataProvider
     */
    public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('user_owner_id', $this->user_owner_id);
		$criteria->compare('item_type', $this->item_type);
		$criteria->compare('create_datetime', $this->create_datetime, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}