<?php

/**
 * This is the model base class for the table "event_view_datetime".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EventViewDatetime".
 *
 * Columns in table "event_view_datetime" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $item_type
 * @property string $update_datetime
 *
 */
abstract class BaseEventViewDatetime extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'event_view_datetime';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EventViewDatetime|EventViewDatetimes', $n);
	}

	public static function representingColumn() {
		return 'update_datetime';
	}

	public function rules() {
		return array(
			array('user_id, item_type, update_datetime', 'required'),
			array('user_id, item_type', 'numerical', 'integerOnly'=>true),
			array('id, user_id, item_type, update_datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'item_type' => Yii::t('app', 'Item Type'),
			'update_datetime' => Yii::t('app', 'Update Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('item_type', $this->item_type);
		$criteria->compare('update_datetime', $this->update_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}