<?php

/**
 * This is the model base class for the table "access".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Access".
 *
 * Columns in table "access" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $user_id
 * @property integer $item_id
 *
 */
abstract class RightsAccess extends MyAR {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'rights';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Access|Accesses', $n);
	}

	public static function representingColumn() {
		return array(
			'user_id',
			'item_id',
		);
	}

	public function rules() {
		return array(
			array('user_id, item_id', 'required'),
			array('user_id, item_id', 'numerical', 'integerOnly'=>true),
			array('user_id, item_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => Yii::t('app', 'User'),
			'item_id' => Yii::t('app', 'Item'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('item_id', $this->item_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}